### ISSUE TITLE
question about shot-sampling

### ISSUE THREAD

**Issue by WMF1997** [chauhanjatin10/GraphsFewShot#2]
hello, 
Thank you for your sharing the code. 
In section 5.2, you write

> The results for all the datasets in various q-shot scenarios

And in your code in src/graphcnn.py
```
				selected_idx = np.random.permutation(len(train_graphs))[:args.batch_size]
				batch_graph = [train_graphs[idx] for idx in selected_idx]
```

I want to ask that:
The "shot" in your article is different from "N-way, K-Shot" in Image Task Meta Learning. 
In Image Task Meta-Learning, we first pick out N classes from meta-train dataset, whose classes is disjoint with that of meta-test dataset. And then, for each picked out classes, K shots are picked out. 
So, ... N * K samples are picked out. And in your article, you just use q shot, "q" has the same meaning with "N * K"?

yours, 
@wmf1997

**Comment by chauhanjatin10** [comment]
Hi @WMF1997,
Thanks for showing interest in our work. Yes, its different from the standard procedure in image few-shot learning. Here, I have picked samples randomly from all classes. I found this worked slightly better in terms of model performance. I have tried to give plausible reasons in the paper. However, you can experiment with the standard methods as well. We have left the standard few-shot learning techniques used in images for future work.
